### ISSUE TITLE
"Please report this error" when trying a graph calendar query

### ISSUE THREAD

**Issue by freeone3000** [microsoftgraph/msgraph-sdk-android#84]
GET https://graph.microsoft.com/v1.0/users/cfma1416@microsoft.com/calendar/events?%24top=500
    SdkVersion : graph-android-v1.7.0
    Authorization : bearer EwBYA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAATiNpIRfUmsSIvLAEJueWMCqX3v5QR/6vPM247/c0d0FY4/vy5Y3EH6XlcrzJRSxyqHM6P+uXEjNsQoa8Fi1Hbb85rGklIGJDx4orPJzsAHcjXMiLQKOJ+EME5Iez+hYVil/WZy7H+rhthJFsGQLnP56p9flsCpWuIFCcmfe86rccCepOi6or6OaieSAcr039KQS+SEPcSMpTRZUgUolqpzct/AfWxMkShlmrYHA+8Rd6efPp1hRe8Syi5804vw9qf50vc5jm+xPgEUT+3jIzFBKw0gtNWhm9KjCsOIlHP8eGZ34/5SDuJNQ5SbUngOboTmIzfHhrv2qAWXQWit/7kYDZgAACK7SctjLsV6iKAJNL1W5PkFEA4tSM7XwgN5o8B2/fnFVRsnYXhtzm/sdr1wHDv/mdSx0PALyUTTs8ViGdGMVQ4y/QoiOfJ5YthDJUbUMmsSn5ny4+lK3B1bayyGDcfFRnR1fxmFTTR3J40jMvLDFOnv/flN65j34lxixPKSoHkEiXJgG7FC+2e0jqjNh8aabbnb5dzzxfYoxqNFSh2C7sCBDcrkmcOAXxfmRDY/g55OBI3kCBo74u9a1eHjqLEkiUy2u41XC/AoaHUqBO4WE+3V+PXBvE8rWVAGjOZUADVHwcNGh/qqNZUMDOIwSTT4L0I7rmw0q9EKfKJY1Y0UwOIikrCW2kzGbv0GT0LC9Dza4SRZhsIbAA4ZcsBcQR6fflf3gniPx60w3zXKLKoSSdwladZrIw+mq742Ut9y7u/9JYcMCqCywXiaFICbdAOzhLUSpTqq4rawn36kVJ2fdZe+lGjmibFB0akhek9rOdz1uiK6URR5Zd/u9QibEkZPmoa9q4C2jDglgCgBEK/4nLgEEQlVkm3K/OXOw4rxmLZ5s0DOwrZ6SAl4H9MOL/zY7PezBsi1TKNgG0ouw2Cs08NpWlbKD30m1VUdf7iOwDmVPcyyvYG0TbWHgqYLjK+UaRI3JBjXeX02GXsEO7rcRIHRK05VuQ5TI0ibBBHE2jNWwJ9y2RWxro2BFv/D/hYNZe/4OoFnVat+cnFKwlf61CGSajZcNNG0IBvPbofCody/fzZxsAg==
    
    
    503 : Service Unavailable
    Transfer-Encoding : chunked
    Duration : 404.6943
    request-id : 3d3bdaa7-dab5-4e35-b845-7b88c9e515f2
    X-Android-Received-Millis : 1530822540892
    Date : Thu, 05 Jul 2018 20:27:46 GMT
    X-Android-Selected-Protocol : http/1.1
    Strict-Transport-Security : max-age=31536000
    Cache-Control : private
    Retry-After : 5
    x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West US 2","Slice":"SliceC","Ring":"4","ScaleUnit":"000","Host":"AGSFE_IN_1","ADSiteName":"WUS2"}}
    client-request-id : 3d3bdaa7-dab5-4e35-b845-7b88c9e515f2
    X-Android-Response-Source : NETWORK 503
    X-Android-Sent-Millis : 1530822540310
    Content-Type : application/json
    {
       "error": {
          "code": "ErrorServiceUnavailable",
          "message": "Active Directory operation did not succeed. Try again later.",
          "innerError": {
             "request-id": "3d3bdaa7-dab5-4e35-b845-7b88c9e515f2",
             "date": "2018-07-05T20:27:46"
          }
       }
    }
    
        at com.microsoft.graph.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:357)
        at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:294)
        at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:190)
        at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:170)
        at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:88)
        at com.microsoft.graph.generated.BaseEventCollectionRequest.get(BaseEventCollectionRequest.java:52)
        at com.maluuba.embedded.example.outlook.OutlookCalendarProvider.getRoomAvailability(OutlookCalendarProvider.kt:102)
        at com.maluuba.embedded.example.outlook.OutlookCalendarProvider.getRoomAvailability(OutlookCalendarProvider.kt:73)
        at com.maluuba.api.client.MaluubaClient.run(Native Method)
        at com.maluuba.api.client.MaluubaClient.run(MaluubaClient.java:37)
        at com.maluuba.embedded.example.MainActivity$DialogueTask.doInBackground(MainActivity.java:274)
        at com.maluuba.embedded.example.MainActivity$DialogueTask.doInBackground(MainActivity.java:260)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by deepak2016** [comment]
834686
Thanks for reporting this issue. We will have a look into this one.

**Comment by nimeesh-msft** [comment]
Do you see this issue happening again? This looks like transient issue. If you have any latest instance of this error, please do share details and we can look into it.
